### ISSUE TITLE
Create a Constants struct items should be nested inside constants in their own structs. There should be a global (this is for things like "ok", project name, etc), there should be an alerts (for alert titles and messages), & should be split by vc.

### ISSUE THREAD

**Issue by cmyers78** [CodeDoesGood/iOS-Template#6]
This has been created and working.  I'm going to give it another day to see if any other items I may want to add pop up.

**Comment by vitalii-tym** [comment]
@cmyers78 Hello Chris, I noticed this issue is in Done column but not yet closed. Is it OK to close it?

**Comment by cmyers78** [comment]
Yes.  sorry.  Thanks!
